import type { AsteroidBeltConfig, OrbitConfig, SunConfig } from "./types";

export const DEFAULT_SPACESHIP_PLANET_ID = "skills";

export const DEFAULT_ASTEROID_BELT: AsteroidBeltConfig = {
    enabled: true,
    innerRadius: 14.8,
    outerRadius: 17.3,
    count: 450,
    minSize: 0.05,
    maxSize: 0.16,
    orbitSpeed: 0.09,
    heightSpread: 0.6,
    inclination: 0.035,
    ascendingNode: 0,
    color: "#9ca3af",
    secondaryColor: "#57534e",
    seed: 101,
};

export const DEFAULT_SUN: SunConfig = {
    id: "home",
    radius: 3.5,
    rotationSpeed: 0.15,
    color: "#ffe59e",
    glowIntensity: 1.3,
    lightIntensity: 6,
    palette: {
        water: "#ffe59e",
        peak: "#fffbeb",
    },
};

export const CENTRAL_BODY: OrbitConfig = {
    id: "home",
    radius: 3.5,
    rotationSpeed: 0.15,
    orbitInclination: 0,
    orbitAscendingNode: 0,
    orbitArgument: 0,
    axialTilt: 0,
    color: "#ffe59e",
    palette: {
        water: "#ffe59e",
        peak: "#fffbeb",
    },
};

export const ORBIT_LAYOUT: OrbitConfig[] = [
    {
        id: "about",
        radius: 0.8,
        rotationSpeed: 0.5,
        orbitRadius: 7,
        orbitSpeed: 0.23,
        initialAngle: 0,
        orbitInclination: 0.122,
        axialTilt: 0.001,
        color: "#ffb15d",
        terrain: {
            seed: 34,
            noiseScale: 1.7,
            roughness: 0.26,
            waterLevel: 0.38,
            detail: 3,
        },
        palette: {
            water: "#c2410c",
            coast: "#f97316",
            land: "#d97706",
            mountain: "#78350f",
            peak: "#fef3c7",
        },
    },
    {
        id: "skills",
        radius: 1.1,
        rotationSpeed: 0.4,
        orbitRadius: 11.2,
        orbitSpeed: 0.137,
        initialAngle: 2.65,
        orbitInclination: 0.059,
        axialTilt: 3.09,
        color: "#5da9ff",
        terrain: {
            seed: 7791,
            noiseScale: 2.25,
            roughness: 0.31,
            waterLevel: 0.36,
            detail: 3,
        },
        palette: {
            water: "#0284c7",
            coast: "#38bdf8",
            land: "#10b981",
            mountain: "#047857",
            peak: "#f8fafc",
        },
        children: [
            {
                id: "skills-moon-1",
                radius: 0.4,
                rotationSpeed: 0.5,
                orbitRadius: 2.2,
                orbitSpeed: 0.93,
                orbitInclination: 0.087,
                axialTilt: 0.026,
                color: "#cbd5e1",
                terrain: {
                    seed: 91,
                    noiseScale: 2.2,
                    roughness: 0.22,
                    waterLevel: 0,
                    detail: 2,
                },
                palette: {
                    land: "#94a3b8",
                    mountain: "#64748b",
                    peak: "#e2e8f0",
                },
            },
        ],
    },
    {
        id: "projects",
        radius: 2.3,
        rotationSpeed: 0.3,
        orbitRadius: 23.8,
        orbitSpeed: 0.071,
        initialAngle: 4.1887902047863905,
        orbitInclination: 0.023,
        axialTilt: 0.054,
        color: "#7dff9c",
        terrain: {
            seed: 73,
            noiseScale: 1.3,
            roughness: 0.25,
            waterLevel: 0.42,
            detail: 3,
        },
        palette: {
            water: "#059669",
            coast: "#10b981",
            land: "#34d399",
            mountain: "#065f46",
            peak: "#ecfdf5",
        },
        ring: {
            innerRadius: 3.21,
            outerRadius: 4.78,
            color: "#6ee7b7",
            opacity: 0.8,
            tilt: [
                1.0471975511965976,
                0,
                0.5235987755982988,
            ],
        },
        children: [
            {
                id: "projects-moon-1",
                radius: 0.22,
                rotationSpeed: 0.7,
                orbitRadius: 5.35,
                orbitSpeed: 0.77,
                orbitInclination: 0.008,
                axialTilt: 0,
                color: "#94a3b8",
                terrain: {
                    seed: 45,
                    noiseScale: 2,
                    roughness: 0.2,
                    waterLevel: 0,
                    detail: 2,
                },
                palette: {
                    land: "#64748b",
                    mountain: "#475569",
                    peak: "#cbd5e1",
                },
            },
            {
                id: "projects-moon-2",
                radius: 0.15,
                rotationSpeed: 1,
                orbitRadius: 6.02,
                orbitSpeed: 0.43,
                orbitInclination: 0.003,
                axialTilt: 0,
                color: "#64748b",
                terrain: {
                    seed: 66,
                    noiseScale: 2.4,
                    roughness: 0.18,
                    waterLevel: 0,
                    detail: 2,
                },
                palette: {
                    land: "#475569",
                    mountain: "#334155",
                    peak: "#94a3b8",
                },
            },
        ],
    },
    {
        id: "contact",
        radius: 1,
        rotationSpeed: 0.6,
        orbitRadius: 32.6,
        orbitSpeed: 0.039,
        initialAngle: 1.5707963267948966,
        orbitInclination: 0.031,
        axialTilt: 0.494,
        color: "#ff5d8f",
        terrain: {
            seed: 88,
            noiseScale: 1.8,
            roughness: 0.24,
            waterLevel: 0.36,
            detail: 3,
        },
        palette: {
            water: "#be185d",
            coast: "#ec4899",
            land: "#a855f7",
            mountain: "#581c87",
            peak: "#fdf2f8",
        },
        children: [
            {
                id: "contact-moon-1",
                radius: 0.18,
                rotationSpeed: 0.5,
                orbitRadius: 2,
                orbitSpeed: 0.61,
                orbitInclination: 0.005,
                axialTilt: 0,
                color: "#cbd5e1",
                terrain: {
                    seed: 19,
                    noiseScale: 2,
                    roughness: 0.2,
                    waterLevel: 0,
                    detail: 2,
                },
                palette: {
                    land: "#94a3b8",
                    mountain: "#64748b",
                    peak: "#f1f5f9",
                },
            },
        ],
    },
];
