import type { OrbitConfig } from "./types";

export const CENTRAL_BODY: OrbitConfig = {
    id: "home",
    radius: 3.5,
    rotationSpeed: 0.15,
    color: "#ffd76b",
    palette: {
        water: "#ffd76b",
        peak: "#fffbeb",
    },
};

export const ORBIT_LAYOUT: OrbitConfig[] = [
    {
        id: "about",
        radius: 1.0,
        rotationSpeed: 0.5,
        orbitRadius: 6,
        orbitSpeed: 0.2,
        initialAngle: 0,
        color: "#5da9ff",
        terrain: {
            seed: 12,
            noiseScale: 1.5,
            roughness: 0.22,
            waterLevel: 0.44,
            detail: 3,
        },
        palette: {
            water: "#0284c7",
            coast: "#38bdf8",
            land: "#10b981",
            mountain: "#047857",
            peak: "#f8fafc",
        },
    },
    {
        id: "skills",
        radius: 1.1,
        rotationSpeed: 0.4,
        orbitRadius: 10,
        orbitSpeed: 0.15,
        initialAngle: Math.PI / 4,
        color: "#ffb15d",
        terrain: {
            seed: 34,
            noiseScale: 1.7,
            roughness: 0.26,
            waterLevel: 0.38,
            detail: 3,
        },
        palette: {
            water: "#c2410c",
            coast: "#f97316",
            land: "#d97706",
            mountain: "#78350f",
            peak: "#fef3c7",
        },
        children: [
            {
                id: "skills-moon-1",
                radius: 0.5,
                rotationSpeed: 0.5,
                orbitRadius: 1.8,
                orbitSpeed: 1,
                color: "#ffe0b2",
                terrain: {
                    seed: 91,
                    noiseScale: 2.0,
                    roughness: 0.18,
                    waterLevel: 0,
                    detail: 2,
                },
                palette: {
                    water: "#fde68a",
                    land: "#d97706",
                    mountain: "#92400e",
                    peak: "#fffbeb",
                },
            },
        ],
    },
    {
        id: "projects",
        radius: 1.5,
        rotationSpeed: 0.3,
        orbitRadius: 14,
        orbitSpeed: 0.1,
        initialAngle: Math.PI / 2,
        color: "#7dff9c",
        terrain: {
            seed: 73,
            noiseScale: 1.3,
            roughness: 0.25,
            waterLevel: 0.42,
            detail: 3,
        },
        palette: {
            water: "#059669",
            coast: "#10b981",
            land: "#34d399",
            mountain: "#065f46",
            peak: "#ecfdf5",
        },
        ring: {
            innerRadius: 2.2,
            outerRadius: 3.3,
            color: "#6ee7b7",
            opacity: 0.8,
            tilt: [Math.PI / 3, 0, Math.PI / 6],
        },
        children: [
            {
                id: "projects-moon-1",
                radius: 0.22,
                rotationSpeed: 0.7,
                orbitRadius: 3.8,
                orbitSpeed: 0.8,
                color: "#b9f6ca",
                terrain: {
                    seed: 45,
                    roughness: 0.15,
                    detail: 2,
                },
                palette: {
                    water: "#a7f3d0",
                    land: "#059669",
                    peak: "#ecfdf5",
                },
            },
            {
                id: "projects-moon-2",
                radius: 0.15,
                rotationSpeed: 1,
                orbitRadius: 4.6,
                orbitSpeed: 0.5,
                color: "#a7f3d0",
                terrain: {
                    seed: 66,
                    roughness: 0.12,
                    detail: 2,
                },
                palette: {
                    water: "#6ee7b7",
                    land: "#047857",
                    peak: "#ffffff",
                },
            },
        ],
    },
    {
        id: "contact",
        radius: 1.0,
        rotationSpeed: 0.6,
        orbitRadius: 18,
        orbitSpeed: 0.08,
        initialAngle: Math.PI,
        color: "#ff5d8f",
        terrain: {
            seed: 88,
            noiseScale: 1.8,
            roughness: 0.24,
            waterLevel: 0.36,
            detail: 3,
        },
        palette: {
            water: "#be185d",
            coast: "#ec4899",
            land: "#a855f7",
            mountain: "#581c87",
            peak: "#fdf2f8",
        },
        children: [
            {
                id: "contact-moon-1",
                radius: 0.18,
                rotationSpeed: 0.5,
                orbitRadius: 1.6,
                orbitSpeed: 0.7,
                color: "#fbcfe8",
                terrain: {
                    seed: 19,
                    roughness: 0.14,
                    detail: 2,
                },
                palette: {
                    water: "#f472b6",
                    land: "#7e22ce",
                    peak: "#ffffff",
                },
            },
        ],
    },
];